backend:
  name: github
  repo: soundbrandingIT/papo-menu-digitale
  branch: main

media_folder: "client/public/uploads"
public_folder: "/uploads"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - name: "menujson"
        label: "Menu JSON"
        file: "client/public/menu.json"
        format: "json"
        fields:
          - label: "Categorie"
            name: "menuData"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Emoji", name: "emoji", widget: "string", required: false }
              - { label: "Descrizione", name: "description", widget: "text", required: false }
              - label: "Prodotti"
                name: "items"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string", required: false }
                  - { label: "Nome", name: "name", widget: "string" }
                  - { label: "Prezzo", name: "price", widget: "number", value_type: "float", required: false }
                  - { label: "Descrizione", name: "description", widget: "text", required: false }
                  - label: "Allergeni"
                    name: "allergens"
                    widget: "list"
                    required: false
                    field: { label: "Allergene", name: "allergen", widget: "string" }
